version: "3.8"

services:
  mysql-users:
    image: mysql:8.0
    container_name: mysql-users
    restart: always
    environment:
      MYSQL_DATABASE: usersdb
      MYSQL_USER: taller
      MYSQL_PASSWORD: taller123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_users_data:/var/lib/mysql

  consul:
    image: consul:1.15
    container_name: consul
    command: consul agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"

volumes:
  mysql_users_data:
